---
title: "mn_sd11_2020"
author: "Luke Kolar"
date: "10/7/2020"
output: html_document
---

```{r, message = F}

## Loading necessary packages...

library(geojsonio)
library(rgdal)
library(raster)
library(rgeos)
library(cowplot)
library(rcartocolor)
library(zipcodeR)
library(broom)
library(sf)
library(janitor)
library(scales)

library(tidyverse)
```

```{r}

## Cleaning precinct datasets

# 2019 precincts

precincts_2019_old <- readOGR( 
  dsn = paste0(getwd(),"/data/vtd_files/2019vtd/"), 
  layer = "bdry_votingdistricts",
  verbose = FALSE) 

precincts_2019_sp <- spTransform(precincts_2019_old, 
            CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))

precincts_2019 <- st_as_sf(precincts_2019_sp) %>% 
  filter(MNSENDIST == "11") %>% 
  mutate(PCTCODE = as.character(PCTCODE)) %>% 
  mutate(COUNTYCODE = as.character(COUNTYCODE))

# 2018 precincts

precincts_2018_old <- readOGR( 
  dsn = paste0(getwd(),"/data/vtd_files/2018vtd/"), 
  layer = "vtd2018general",
  verbose = FALSE) 

precincts_2018_sp <- spTransform(precincts_2018_old, 
            CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))

precincts_2018 <- st_as_sf(precincts_2018_sp) %>% 
  filter(MNSENDIST == "11") %>% 
  mutate(PCTCODE = as.character(PCTCODE)) %>% 
  mutate(COUNTYCODE = as.character(COUNTYCODE))

# 2016 precincts

precincts_2016_old <- readOGR( 
  dsn = paste0(getwd(),"/data/vtd_files/2016vtd/"), 
  layer = "vtd2016general",
  verbose = FALSE) 

precincts_2016_sp <- spTransform(precincts_2016_old, 
            CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))

precincts_2016 <- st_as_sf(precincts_2016_sp) %>% 
  filter(MNSENDIST == "11") %>% 
  mutate(PCTCODE = as.character(PCTCODE)) %>% 
  mutate(COUNTYCODE = as.character(COUNTYCODE))

# 2014 precincts

precincts_2014_old <- readOGR( 
  dsn = paste0(getwd(),"/data/vtd_files/2014vtd/"), 
  layer = "vtd2014general",
  verbose = FALSE) 

precincts_2014_sp <- spTransform(precincts_2014_old, 
            CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))

precincts_2014 <- st_as_sf(precincts_2014_sp) %>% 
  filter(MNSENDIST == "11") %>% 
  mutate(PCTCODE = as.character(PCTCODE)) %>% 
  mutate(COUNTYCODE = as.character(COUNTYCODE))

# 2012 precincts

precincts_2012_old <- readOGR( 
  dsn = paste0(getwd(),"/data/vtd_files/2012vtd/"), 
  layer = "vtd2012general",
  verbose = FALSE) 

precincts_2012_sp <- spTransform(precincts_2012_old, 
            CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"))

precincts_2012 <- st_as_sf(precincts_2012_sp) %>% 
  rename(MNLEGDIST = LEGDIST) %>% 
  mutate(MNLEGDIST = as.character(MNLEGDIST)) %>% 
  mutate(MNSENDIST = str_match(MNLEGDIST, "[:digit:]*")) %>% 
  mutate(MNLEGDIST = as.factor(MNLEGDIST),
         MNSENDIST = as.factor(MNSENDIST)) %>% 
  select(!SENDIST) %>% 
  filter(MNSENDIST == "11") %>% 
  mutate(PCTCODE = as.character(PCTCODE)) %>% 
  mutate(COUNTYCODE = as.character(COUNTYCODE))

```

```{r}

## Testing precinct maps...

ggplot(precincts_2019 %>% filter(MNSENDIST == "11"), aes(fill = MNLEGDIST)) + 
  geom_sf(color = "grey30", lwd = 0.25) + 
  theme_void()

ggplot(precincts_2018 %>% filter(MNSENDIST == "11"), aes(fill = MNLEGDIST)) + 
  geom_sf(color = "grey30", lwd = 0.25) + 
  theme_void()

ggplot(precincts_2016 %>% filter(MNSENDIST == "11"), aes(fill = MNLEGDIST)) + 
  geom_sf(color = "grey30", lwd = 0.25) + 
  theme_void()

ggplot(precincts_2014 %>% filter(MNSENDIST == "11"), aes(fill = MNLEGDIST)) + 
  geom_sf(color = "grey30", lwd = 0.25) + 
  theme_void()

ggplot(precincts_2012 %>% filter(MNSENDIST == "11"), aes(fill = MNLEGDIST)) + 
  geom_sf(color = "grey30", lwd = 0.25) + 
  theme_void()

```


```{r}

## Cleaning precinct reporting statistics by year

prec.col.names <- c("state", "county_id", "precinct_num",
                    "precinct_name", "reported", "reg_voters_7am", 
                    "reg_voters_eday", "num_signatures",
                    "num_reg_absentee", "num_fed_only_absentee", 
                    "num_pres_only_absentee", "total_voted")

# 2019

report_2019 <- read.delim("data/pctstats/2019pctstats_special.txt", 
  sep = ";", header = FALSE, col.names = prec.col.names) %>% 
  mutate(precinct_num = sprintf("%04d", precinct_num)) %>% 
  mutate(precinct_num = as.character(precinct_num)) %>% 
  mutate(total_reg = reg_voters_7am + reg_voters_eday) %>% 
  mutate(total_perc_voted = 100*(total_voted / total_reg),
         total_perc_voted_without_eday = 
           100*((total_voted - reg_voters_eday) / reg_voters_7am)) %>% 
  mutate(total_perc_voted = ifelse(is.nan(total_perc_voted), 0, total_perc_voted),
         total_perc_voted_without_eday = 
           ifelse(is.nan(total_perc_voted_without_eday), 0, total_perc_voted_without_eday)) %>% 
  mutate(county_id = as.character(county_id))

# 2018

report_2018 <- read.delim("data/pctstats/2018pctstats_general.txt", 
  sep = ";", header = FALSE, col.names = prec.col.names) %>% 
  mutate(precinct_num = sprintf("%04d", precinct_num)) %>% 
  mutate(precinct_num = as.character(precinct_num)) %>% 
  mutate(total_reg = reg_voters_7am + reg_voters_eday) %>% 
  mutate(total_perc_voted = 100*(total_voted / total_reg),
         total_perc_voted_without_eday = 
           100*((total_voted - reg_voters_eday) / reg_voters_7am)) %>% 
  mutate(total_perc_voted = ifelse(is.nan(total_perc_voted), 0, total_perc_voted),
         total_perc_voted_without_eday = 
           ifelse(is.nan(total_perc_voted_without_eday), 0, total_perc_voted_without_eday)) %>% 
  mutate(county_id = as.character(county_id))

# 2016

report_2016 <- read.delim("data/pctstats/2016pctstats_general.txt", 
  sep = ";", header = FALSE, col.names = prec.col.names) %>% 
  mutate(precinct_num = sprintf("%04d", precinct_num)) %>% 
  mutate(precinct_num = as.character(precinct_num)) %>% 
  mutate(total_reg = reg_voters_7am + reg_voters_eday) %>% 
  mutate(total_perc_voted = 100*(total_voted / total_reg),
         total_perc_voted_without_eday = 
           100*((total_voted - reg_voters_eday) / reg_voters_7am)) %>% 
  mutate(total_perc_voted = ifelse(is.nan(total_perc_voted), 0, total_perc_voted),
         total_perc_voted_without_eday = 
           ifelse(is.nan(total_perc_voted_without_eday), 0, total_perc_voted_without_eday)) %>% 
  mutate(county_id = as.character(county_id))

# 2014

report_2014 <- read.delim("data/pctstats/2014pctstats_general.txt", 
  sep = ";", header = FALSE, col.names = prec.col.names) %>% 
  mutate(precinct_num = sprintf("%04d", precinct_num)) %>% 
  mutate(precinct_num = as.character(precinct_num)) %>% 
  mutate(total_reg = reg_voters_7am + reg_voters_eday) %>% 
  mutate(total_perc_voted = 100*(total_voted / total_reg),
         total_perc_voted_without_eday = 
           100*((total_voted - reg_voters_eday) / reg_voters_7am)) %>% 
  mutate(total_perc_voted = ifelse(is.nan(total_perc_voted), 0, total_perc_voted),
         total_perc_voted_without_eday = 
           ifelse(is.nan(total_perc_voted_without_eday), 0, total_perc_voted_without_eday)) %>% 
  mutate(county_id = as.character(county_id))

# 2012

report_2012 <- read.delim("data/pctstats/2012pctstats_general.txt", 
  sep = ";", header = FALSE, col.names = prec.col.names) %>% 
  mutate(precinct_num = sprintf("%04d", precinct_num)) %>% 
  mutate(precinct_num = as.character(precinct_num)) %>% 
  mutate(total_reg = reg_voters_7am + reg_voters_eday) %>% 
  mutate(total_perc_voted = 100*(total_voted / total_reg),
         total_perc_voted_without_eday = 
           100*((total_voted - reg_voters_eday) / reg_voters_7am)) %>% 
  mutate(total_perc_voted = ifelse(is.nan(total_perc_voted), 0, total_perc_voted),
         total_perc_voted_without_eday = 
           ifelse(is.nan(total_perc_voted_without_eday), 0, total_perc_voted_without_eday)) %>% 
  mutate(county_id = as.character(county_id))

```


```{r}

## Cleaning election data for 11A and 11B

elec.col.names <- c("state", "county_id", "precinct_num",
                    "office_id", "office_name", "district", 
                    "candidate_order_code", "candidate_name",
                    "suffix", "incumbent_code", "party_affiliation",
                    "num_precincts_reporting", "total_num_precincts_voting",
                    "candidate_votes", "candidate_percent_vote", "total_race_votes")

# 2018 reps

prec_2018 <- read.delim("data/precinct_level_state_leg/2018_reps.txt", 
  sep = ";", header = FALSE, col.names = elec.col.names) %>% 
  mutate(precinct_num = sprintf("%04d", precinct_num)) %>% 
  mutate(precinct_num = as.character(precinct_num))

prec_2018_wide <- prec_2018 %>% 
  select(precinct_num, district, county_id, party_affiliation, 
         candidate_votes, total_race_votes) %>% 
  filter(district %in% c("11A", "11B")) %>% 
  pivot_wider(names_from = party_affiliation, values_from = candidate_votes) %>% 
  mutate(R_perc = 100*(R/total_race_votes),
         DFL_perc = 100*(DFL/total_race_votes)) %>% 
  select(precinct_num, district, county_id, DFL, R, 
         DFL_perc, R_perc, total_race_votes, WI) %>% 
  mutate(county_id = as.character(county_id))

prec_elec_map_2018 <- precincts_2018 %>%
  inner_join(prec_2018_wide, by = c("PCTCODE" = "precinct_num",
                                    "COUNTYCODE" = "county_id")) %>% 
  inner_join(report_2018, by = c("PCTCODE" = "precinct_num", 
                                 "COUNTYCODE" = "county_id"))

# 2016 reps

prec_2016 <- read.delim("data/precinct_level_state_leg/2016_reps.txt", 
  sep = ";", header = FALSE, col.names = elec.col.names) %>% 
  mutate(precinct_num = sprintf("%04d", precinct_num)) %>% 
  mutate(precinct_num = as.character(precinct_num))

prec_2016_wide <- prec_2016 %>% 
  select(precinct_num, district, county_id, party_affiliation, 
         candidate_votes, total_race_votes) %>% 
  filter(district %in% c("11A", "11B")) %>% 
  pivot_wider(names_from = party_affiliation, values_from = candidate_votes) %>% 
  mutate(R_perc = 100*(R/total_race_votes),
         DFL_perc = 100*(DFL/total_race_votes)) %>% 
  select(precinct_num, district, county_id, DFL, R, 
         DFL_perc, R_perc, total_race_votes, WI) %>% 
  mutate(county_id = as.character(county_id))

prec_elec_map_2016 <- precincts_2016 %>%
  inner_join(prec_2016_wide, by = c("PCTCODE" = "precinct_num",
                                    "COUNTYCODE" = "county_id")) %>%
  inner_join(report_2016, by = c("PCTCODE" = "precinct_num", 
                                 "COUNTYCODE" = "county_id"))

# 2014 reps

prec_2014 <- read.delim("data/precinct_level_state_leg/2014_reps.txt", 
  sep = ";", header = FALSE, col.names = elec.col.names) %>% 
  mutate(precinct_num = sprintf("%04d", precinct_num)) %>% 
  mutate(precinct_num = as.character(precinct_num))

prec_2014_wide <- prec_2014 %>% 
  select(precinct_num, district, county_id, party_affiliation, 
         candidate_votes, total_race_votes) %>% 
  filter(district %in% c("11A", "11B")) %>% 
  pivot_wider(names_from = party_affiliation, values_from = candidate_votes) %>% 
  mutate(R_perc = 100*(R/total_race_votes),
         DFL_perc = 100*(DFL/total_race_votes)) %>% 
  select(precinct_num, district, county_id, DFL, R, 
         DFL_perc, R_perc, total_race_votes, WI) %>% 
  mutate(county_id = as.character(county_id))

prec_elec_map_2014 <- precincts_2014 %>%
  inner_join(prec_2014_wide, by = c("PCTCODE" = "precinct_num",
                                    "COUNTYCODE" = "county_id")) %>%
  inner_join(report_2014, by = c("PCTCODE" = "precinct_num", 
                                 "COUNTYCODE" = "county_id"))

# 2012 reps

prec_2012 <- read.delim("data/precinct_level_state_leg/2012_reps.txt", 
  sep = ";", header = FALSE, col.names = elec.col.names) %>% 
  mutate(precinct_num = sprintf("%04d", precinct_num)) %>% 
  mutate(precinct_num = as.character(precinct_num))

prec_2012_wide <- prec_2012 %>% 
  select(precinct_num, district, county_id, party_affiliation, 
         candidate_votes, total_race_votes) %>% 
  filter(district %in% c("11A", "11B")) %>% 
  pivot_wider(names_from = party_affiliation, values_from = candidate_votes) %>% 
  mutate(R_perc = 100*(R/total_race_votes),
         DFL_perc = 100*(DFL/total_race_votes)) %>% 
  select(precinct_num, district, county_id, DFL, R, 
         DFL_perc, R_perc, total_race_votes, WI) %>% 
  mutate(county_id = as.character(county_id))

prec_elec_map_2012 <- precincts_2012 %>%
  inner_join(prec_2012_wide, by = c("PCTCODE" = "precinct_num",
                                    "COUNTYCODE" = "county_id")) %>%
  inner_join(report_2012, by = c("PCTCODE" = "precinct_num", 
                                 "COUNTYCODE" = "county_id"))

```

```{r}

## 11A and 11B precinct maps by year, testing fill gradient scales...

ggplot(prec_elec_map_2018, aes(fill = total_perc_voted)) + 
  geom_sf(color = "grey30", lwd = 0.25) + 
  theme_void() + scale_fill_gradient(low = "white", high = "blue")

ggplot(prec_elec_map_2016, aes(fill = total_perc_voted)) + 
  geom_sf(color = "grey30", lwd = 0.25) + 
  theme_void() + scale_fill_gradient(low = "white", high = "blue")

ggplot(prec_elec_map_2014, aes(fill = total_perc_voted)) + 
  geom_sf(color = "grey30", lwd = 0.25) + 
  theme_void() + scale_fill_gradient(low = "white", high = "blue")

ggplot(prec_elec_map_2012, aes(fill = total_perc_voted)) + 
  geom_sf(color = "grey30", lwd = 0.25) + 
  theme_void() + scale_fill_gradient(low = "white", high = "blue")

```

```{r}


## Cleaning election data for 11

elec.col.names <- c("state", "county_id", "precinct_num",
                    "office_id", "office_name", "district", 
                    "candidate_order_code", "candidate_name",
                    "suffix", "incumbent_code", "party_affiliation",
                    "num_precincts_reporting", "total_num_precincts_voting",
                    "candidate_votes", "candidate_percent_vote", "total_race_votes")

# 2019 special senate

prec_2019_sen <- read.delim("data/precinct_level_state_leg/2019_senate_special.txt", 
  sep = ";", header = FALSE, col.names = elec.col.names) %>% 
  mutate(precinct_num = sprintf("%04d", precinct_num)) %>% 
  mutate(precinct_num = as.character(precinct_num))

prec_2019_wide_sen <- prec_2019_sen %>% 
  select(precinct_num, district, county_id, party_affiliation, 
         candidate_votes, total_race_votes) %>%
  filter(district == "11") %>% 
  pivot_wider(names_from = party_affiliation, values_from = candidate_votes) %>%
  mutate(R_perc = 100*(R/total_race_votes),
         DFL_perc = 100*(DFL/total_race_votes)) %>% 
  select(precinct_num, district, county_id, DFL, R, 
         DFL_perc, R_perc, total_race_votes, WI) %>% 
  mutate(county_id = as.character(county_id))

prec_elec_map_2019_sen <- precincts_2019 %>%
  inner_join(prec_2019_wide_sen, by = c("PCTCODE" = "precinct_num",
                                    "COUNTYCODE" = "county_id")) %>%
  inner_join(report_2019, by = c("PCTCODE" = "precinct_num", 
                                 "COUNTYCODE" = "county_id"))

# 2016 senate

prec_2016_sen <- read.delim("data/precinct_level_state_leg/2016_senate.txt", 
  sep = ";", header = FALSE, col.names = elec.col.names) %>% 
  mutate(precinct_num = sprintf("%04d", precinct_num)) %>% 
  mutate(precinct_num = as.character(precinct_num))

prec_2016_wide_sen <- prec_2016_sen %>% 
  select(precinct_num, district, county_id, party_affiliation, 
         candidate_votes, total_race_votes) %>%
  filter(district == "11") %>% 
  pivot_wider(names_from = party_affiliation, values_from = candidate_votes) %>%
  mutate(R_perc = 100*(R/total_race_votes),
         DFL_perc = 100*(DFL/total_race_votes)) %>% 
  select(precinct_num, district, county_id, DFL, R, 
         DFL_perc, R_perc, total_race_votes, WI) %>% 
  mutate(county_id = as.character(county_id))

prec_elec_map_2016_sen <- precincts_2016 %>%
  inner_join(prec_2016_wide_sen, by = c("PCTCODE" = "precinct_num",
                                    "COUNTYCODE" = "county_id")) %>%
  inner_join(report_2016, by = c("PCTCODE" = "precinct_num", 
                                 "COUNTYCODE" = "county_id"))

# 2012 senate

prec_2012_sen <- read.delim("data/precinct_level_state_leg/2012_senate.txt", 
  sep = ";", header = FALSE, col.names = elec.col.names) %>% 
  mutate(precinct_num = sprintf("%04d", precinct_num)) %>% 
  mutate(precinct_num = as.character(precinct_num))

prec_2012_wide_sen <- prec_2012_sen %>% 
  select(precinct_num, district, county_id, party_affiliation, 
         candidate_votes, total_race_votes) %>%
  filter(district == "11") %>% 
  pivot_wider(names_from = party_affiliation, values_from = candidate_votes) %>%
  mutate(R_perc = 100*(R/total_race_votes),
         DFL_perc = 100*(DFL/total_race_votes)) %>% 
  select(precinct_num, district, county_id, DFL, R, 
         DFL_perc, R_perc, total_race_votes, WI) %>% 
  mutate(county_id = as.character(county_id))

prec_elec_map_2012_sen <- precincts_2012 %>%
  inner_join(prec_2012_wide_sen, by = c("PCTCODE" = "precinct_num",
                                    "COUNTYCODE" = "county_id")) %>%
  inner_join(report_2012, by = c("PCTCODE" = "precinct_num", 
                                 "COUNTYCODE" = "county_id"))

```

```{r}

ggplot(prec_elec_map_2019_sen, aes(fill = R_perc)) + 
  geom_sf(color = "grey30", lwd = 0.25) + 
  theme_void() + scale_fill_gradient(low = "white", high = "red") + 
  labs(title = "2019 State Senate Special Election")

ggplot(prec_elec_map_2016_sen, aes(fill = R_perc)) + 
  geom_sf(color = "grey30", lwd = 0.25) + 
  theme_void() + scale_fill_gradient(low = "white", high = "red") + 
  labs(title = "2016 State Senate Election")

ggplot(prec_elec_map_2012_sen, aes(fill = R_perc)) + 
  geom_sf(color = "grey30", lwd = 0.25) + 
  theme_void() + scale_fill_gradient(low = "white", high = "red") + 
  labs(title = "2012 State Senate Election")

ggplot(prec_elec_map_2019_sen, aes(fill = total_race_votes)) + 
  geom_sf(color = "grey30", lwd = 0.25) + 
  theme_void() + scale_fill_gradient(low = "white", high = "purple") + 
  labs(title = "2019 State Senate Special Election")

ggplot(prec_elec_map_2016_sen, aes(fill = total_race_votes)) + 
  geom_sf(color = "grey30", lwd = 0.25) + 
  theme_void() + scale_fill_gradient(low = "white", high = "purple") + 
  labs(title = "2016 State Senate Election")

ggplot(prec_elec_map_2019_sen, aes(fill = total_perc_voted)) + 
  geom_sf(color = "grey30", lwd = 0.25) + 
  theme_void() + scale_fill_gradient(low = "white", high = "blue") + 
  labs(title = "2019 State Senate Special Election")

ggplot(prec_elec_map_2016_sen, aes(fill = total_perc_voted)) + 
  geom_sf(color = "grey30", lwd = 0.25) + 
  theme_void() + scale_fill_gradient(low = "white", high = "blue") + 
  labs(title = "2016 State Senate Election")

ggplot(prec_elec_map_2012_sen, aes(fill = total_perc_voted)) + 
  geom_sf(color = "grey30", lwd = 0.25) + 
  theme_void() + scale_fill_gradient(low = "white", high = "blue") + 
  labs(title = "2012 State Senate Election")

```

```{r}


rbind((prec_elec_map_2012_sen %>% 
                mutate(column = "2012", overallDFL = 64.3) %>% select(district:overallDFL)), 
             (prec_elec_map_2016_sen %>% 
                mutate(column = "2016", overallDFL = 54.6) %>% select(district:overallDFL)), 
             (prec_elec_map_2019_sen %>% 
                mutate(column = "2019", overallDFL = 45.9) %>% select(district:overallDFL))) %>% glimpse()

label.fillers <- tibble(district = c(NA, NA, NA), DFL = c(NA, NA, NA), 
                        R = c(NA, NA, NA), DFL_perc = c(NA, NA, NA), 
                        R_perc = c(NA, NA, NA), total_race_votes = c(NA, NA, NA), 
                        WI = c(NA, NA, NA), state = c("MN", "MN", "MN"), 
                        precinct_name = c("[filler]", "[filler]", "[filler]"), 
                        reported = c(NA, NA, NA), reg_voters_7am = c(NA, NA, NA), 
                        reg_voters_eday = c(NA, NA, NA), num_signatures = c(NA, NA, NA), 
                        num_reg_absentee = c(NA, NA, NA), 
                        num_fed_only_absentee = c(NA, NA, NA), 
                        num_pres_only_absentee = c(NA, NA, NA), 
                        total_voted = c(NA, NA, NA), total_reg = c(NA, NA, NA), 
                        total_perc_voted = c(NA, NA, NA), 
                        total_perc_voted_without_eday = c(NA, NA, NA), 
                        year = c("2012", "2016", "2019"), overallDFL = c(64.3, 54.6, 45.9), 
                        year_label = c("2012", "2016", "2019"))

ggplot(rbind((as_tibble(prec_elec_map_2012_sen %>% 
                mutate(year = "2012", overallDFL = NA, year_label = NA)) %>%
                select(district:year_label) %>% select(!geometry)), 
             (as_tibble(prec_elec_map_2016_sen %>% 
                mutate(year = "2016", overallDFL = NA, year_label = NA)) %>%
                select(district:year_label) %>% select(!geometry)), 
             (as_tibble(prec_elec_map_2019_sen %>% 
                mutate(year = "2019", overallDFL = NA, year_label = NA)) %>%
                select(district:year_label) %>% select(!geometry)), (label.fillers)), 
       aes(x = DFL_perc, y = total_race_votes, color = DFL_perc)) +
  geom_point(aes()) + facet_wrap(~year) +  scale_color_gradient(low = "red", high  = "blue") +
  labs(x = "Percent Voted DFL", y = "Precinct Total Votes", 
       title = "MN SD11 Total Votes and Percent DFL by Precinct") + 
  geom_vline(aes(xintercept = overallDFL), linetype = "dotted", color = "blue") +
  geom_label(aes(x = 18, y = 2850, label = year_label), fill = "white", color = "black",
            size = 4, family = "Verdana", fontface = "bold") +
  geom_text(aes(color = overallDFL, x = as.numeric(overallDFL), y = 2400, vjust = -0.7, angle = -90,
                 label = paste0("DFL: ", overallDFL, "%")), size = 3, family = "Verdana") + 
  scale_x_continuous(limits = c(1, 100), expand = c(0, 0)) +
  scale_y_continuous(label = comma, limits = c(0, 3000), expand = c(0, 0)) +
  theme(legend.position = "none",
        panel.grid.minor = element_blank(),
        axis.text.y = element_text(angle = 45, hjust = 1),
        axis.text.x = element_text(angle = 45, hjust = 1.1),
        panel.grid = element_line(color = "light grey"),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", fill = NA),
        strip.background = element_blank(),
        strip.text = element_blank(),
        plot.title = element_text(face = "bold", hjust = 0.5),
        axis.title = element_text(face = "italic"),
        text = element_text(family = "Verdana"),
        axis.title.y = element_text(vjust = 1),
        panel.spacing = unit(12, "points"))


?geom_label
```


```{r}
?element_t

?strip.placement

?unit

?geom_label

```


```{r}

(prec_elec_map_2019_sen %>% 
                mutate(column = "2012", overallDFL = 64.3) %>% 
                select(district:overallDFL, geometry)) %>% nrow


rbind((prec_elec_map_2012_sen %>% 
                mutate(column = "2012", overallDFL = 64.3) %>% 
                select(district:overallDFL, geometry)), 
             (prec_elec_map_2016_sen %>% 
                mutate(column = "2016", overallDFL = 54.6) %>% 
                select(district:overallDFL, geometry)), 
             (prec_elec_map_2019_sen %>% 
                mutate(column = "2019", overallDFL = 45.9) %>% 
                select(district:overallDFL, geometry))) %>% nrow

(prec_elec_map_2012_sen %>% 
                mutate(column = "2012", overallDFL = 64.3) %>% 
                select(district:overallDFL, geometry) %>% 
  cbind(year_label = c("2012", rep(NA, times = 103)),
        overallDFL_label = c(64.3, rep(NA, times = 103))))


ggplot(rbind((prec_elec_map_2012_sen %>% 
                mutate(year = "2012", overallDFL = 64.3) %>% 
                select(district:overallDFL, geometry) %>% 
                cbind(year_label = c("2012", rep(NA, times = 103)),
                      overallDFL_label = c(64.3, rep(NA, times = 103)))), 
             (prec_elec_map_2016_sen %>% 
                mutate(year = "2016", overallDFL = 54.6) %>% 
                select(district:overallDFL, geometry)) %>% 
                cbind(year_label = c("2016", rep(NA, times = 102)),
                      overallDFL_label = c(54.6, rep(NA, times = 102))), 
             (prec_elec_map_2019_sen %>% 
                mutate(year = "2019", overallDFL = 45.9) %>% 
                select(district:overallDFL, geometry) %>% 
                cbind(year_label = c("2019", rep(NA, times = 102)),
                      overallDFL_label = c(45.9, rep(NA, times = 102))))), 
       aes(fill = total_perc_voted)) + geom_sf(color = "grey30", lwd = 0.25) + 
  theme_void() + scale_fill_gradient(low = "white", high = "purple",
                                     labels = c("0%", "25%", "50%", "75%", "100%")) + 
  facet_wrap(~year) + geom_label(aes(y = 46.9, x = -93.25, label = year_label), fill = "NA", 
                                   size = 4, family = "Verdana", fontface = "bold") + 
  labs(title = "MN SD11 Registered Voter Turnout by Precinct", 
       caption = "note: registered voter turnout is not\nthe same as eligible voter turnout") +
  theme(legend.position = "bottom",
        strip.text = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size = 7),
        plot.title = element_text(face = "bold", hjust = 0.5),
        text = element_text(family = "Verdana"),
        legend.key.size = unit(9, "pt"),
        legend.key.width = unit(25, "pt"),
        plot.caption = element_text(face = "italic", size = 5, vjust = 5))
  


geom_label(aes(y = 46.9, x = 93.25, label = column), 
            size = 4, family = "Verdana", fontface = "bold")

```

```{r}

rbind((as_tibble(prec_elec_map_2012_sen %>% 
            mutate(year = "2012")) %>%
            select(district:year) %>% select(!geometry)), 
      (as_tibble(prec_elec_map_2016_sen %>% 
            mutate(year = "2016")) %>%
            select(district:year) %>% select(!geometry)), 
      (as_tibble(prec_elec_map_2019_sen %>% 
            mutate(year = "2019")) %>%
            select(district:year) %>% select(!geometry))) %>% 
  pivot_wider(names_from = year, values_from = c(DFL, R, DFL_perc, R_perc, 
                                                 total_race_votes, WI, reg_voters_7am,
                                                 reg_voters_eday, num_signatures,
                                                 num_reg_absentee, num_fed_only_absentee,
                                                 num_pres_only_absentee, total_voted,
                                                 total_reg, total_perc_voted,
                                                 total_perc_voted_without_eday,
                                                 )) %>% 
  mutate


```








